// SAMPLE report — fictional product, invented findings, illustrative only.
// This is the example that ships with the template; it exercises every
// block type. Replace this file's data with a real teardown to use it.
// All styling lives in teardown.typ. Mirrors report-data.js: swap data,
// get the same render.

#import "teardown.typ": *

#report(
  meta: (
    kicker:        "Marketing & Copy Teardown",
    title:         "acme.example — Sample Marketing & Copy Teardown",
    titleMain:     "acme",
    titleAccent:   ".example",
    subtitle:      "Proof before promise. Wedge before noise. Clarity before checkout.",
    dek:           [A worked *sample* showing the teardown format end to end. The subject — “Acme”, a fictional product analytics SaaS at a reserved `.example` domain — and every finding below are invented to illustrate the structure. Swap in a real product to use this as a template.],
    basis:         [Sample report. Fictional product, invented copy and findings — illustrative only, not based on any real company. Competitor names in #ic[Appendix A] are placeholders.],
    author:        "marketing-may",
    reportNumber:  "00",
    dateline:      "2026 · 05 · 15",
    readTime:      "12 min",
    year:          "2026",
    colophonLeft:  "acme.example · Sample Marketing Teardown",
    colophonMid:   "End of sample",
  ),

  tldr-lede: [Your copy is not the problem. The hero line is competent. The problem is that *the copy is doing the wrong job in the wrong order*, on top of an offer that asks for a credit card before it has earned belief, with a pricing page that contradicts itself and the homepage.],

  priorities: (
    (
      n: "01",
      title: [Earn belief before asking for the card.],
      body: [A bold, unbenchmarked accuracy claim, no free trial, and three logos no one recognizes is a credibility gap, not a copy gap. No headline rewrite survives it. Ship a self-serve trial, show the product working, lead with the guarantee.],
    ),
    (
      n: "02",
      title: [Pick one positioning.],
      body: [You are selling “unified analytics” (commoditized — Northstar, Metricly, Funnelhouse own it) when your only defensible wedge is no-instrumentation session capture. Lead with the wedge; demote the dashboard to a proof point.],
    ),
    (
      n: "03",
      title: [De-confuse the pricing page.],
      body: [It is four documents fighting on one page (SaaS price sheet / usage meter / enterprise gate / capability flex). It answers neither question a pricing page exists to answer: what will I pay? and what's my downside?],
    ),
  ),

  tldr-closer: [This is a copy/positioning critique, not a decision-grade pricing commit, so it deliberately does not prescribe price numbers — a real engagement would have willingness-to-pay evidence; the correct output here is a structure plus a price test, not a price.],

  sections: (
    section("01", [What the product actually is], kicker: "Extracted facts",
      kv(
        ([Category], [Product analytics / session-capture SaaS.]),
        ([Core mechanic], [Drop one snippet on the site. Acme auto-captures every click, route, and form interaction — no manual event tagging — then reconstructs funnels and session replays. Billed per monthly tracked user against a tiered plan.]),
      ),
      h3([Differentiators claimed]),
      ul(
        [Zero-instrumentation capture — “no engineers, no event taxonomy, live in five minutes.”],
        [Replay + funnels + heatmaps in _one_ tool.],
        [“Privacy-first”: PII auto-masked, EU data residency on higher tiers.],
        [“Models accuracy beats the category leaders” — no benchmark cited.],
      ),
      h3([Commercial state]),
      p([Live and self-serve in theory, but the homepage routes every CTA to *Book a demo*. A 14-day trial exists and is mentioned only on the pricing page. Headline social proof is three unfamiliar logos and one unattributed pull quote. Founder/team page is a single paragraph with no names.]),
      p([Full sample of the extracted copy is in #xref("appendix-a")[Appendix A].]),
    ),

    section("02", [Critical unknowns], kicker: "Resolve these or no copy fix is reliable",
      p([At least the first two are _validity preconditions_ — if the assumption is wrong, the entire approach is invalid, not merely sub-optimal.]),
      etable(
        columns: (30pt, 1.3fr, 1.6fr, 1.4fr),
        head: ([\#], [Unknown], [Why it can invalidate everything], [Cheapest way to learn]),
        rows: (
          (nc[1],
           [#precondition Activation reality. Does the “five-minute, zero-instrumentation” promise actually hold for a real site, or does it need a data layer, a CSP exception, and an engineer?],
           [If setup truly needs engineering, the entire wedge (“no engineers”) is false and every hero variant built on it misleads — churn and refund risk, not just weak conversion.],
           [Install the snippet on three real test sites yourself; time to first usable funnel. Half a day.]),
          (nc[2],
           [#precondition Cold-traffic trust floor. Will a _cold_ buyer start a trial for an analytics tool that captures “everything” with no recognizable proof and no named team?],
           [If no, the blocker is the _offer and proof_, not the words. Demo-booked leads are sales-warmed and do not predict self-serve conversion (selection bias).],
           [Show the live page to 8 target PMs (or 5 unmoderated tests): “Would you start this trial? What stops you?” ~\$0–60, 1 day.]),
          (nc[3],
           [#precondition Privacy claim is real. Is PII masking on by default and contractually backed, or a config flag and a blog post?],
           [“Privacy-first” while capturing all interactions is a legal and trust landmine. If it's not real and default, the claim must come down before any campaign ships.],
           [Read the masking defaults and DPA; capture a session on a form page and inspect what was stored. 2 hours.]),
          (nc[4],
           [ICP ambiguity. Buyer = product managers, growth marketers, or front-end engineers? Each needs a different hero and proof.],
           [Targeting all three converts none.],
           [Read the free-text “what will you use Acme for?” answers already captured at trial signup; skim support tickets for role signals.]),
          (nc[5],
           [Flat vs. usage billing. The page says “simple flat plans” _and_ “billed per tracked user, overage \$0.002 each.”],
           [This is the single fact a buyer needs to evaluate the offer. Until resolved, they cannot predict the bill.],
           [One sentence stating the billing rule + one worked invoice example.]),
        ),
      ),
    ),

    section("03", [Diagnosis], kicker: "Where the marketing actually breaks",
      h3([3.1 Belief is the dominant constraint, not copy polish]),
      p([A cold visitor sees *a tool that captures everything, an unbenchmarked “beats the leaders” claim, three unknown logos, no named team, and no way to try it without a sales call*. Every item is individually a small doubt; stacked, they read as “unproven” to anyone who isn't already a referral.]),
      p([The page leads with _features_ (the most commoditized story in analytics) and _a demo gate_ (friction before value), while the actual conversion blocker — _“is this real, is it safe to point at my users, and will it actually work without an engineer?”_ — is unaddressed anywhere.]),
      quote-pull([Polishing the headline cannot fix a credibility-architecture problem. The marketing job here is proof engineering; copy is downstream of it.]),
      p([The demo-only homepage is a self-inflicted wound: every self-serve-inclined visitor who wanted to just try it bounced _and never saw the product work_. A gated page must still show the product doing its job.]),
      h3([3.2 Positioning is muddled — you're competing in the wrong lane]),
      p([Three different products are fighting inside this site:]),
      ol(
        [*Unified analytics dashboard* — “funnels, retention, dashboards.” Commoditized; Northstar, Metricly and Funnelhouse own the category and the comparison pages. You will not win here.],
        [*Session replay tool* — watch real user sessions; a crowded but smaller field.],
        [*Zero-instrumentation capture* — point it at any site, get analytics with no event taxonomy and no engineering.],
      ),
      p([*(c) is the only defensible wedge* — few competitors offer genuinely tag-free capture. Your own onboarding proves it: the “five minutes, no engineers” path is the one thing reviewers consistently praise. Yet the hero leads with (a), the commoditized lane.]),
      h3([3.3 Named dominant alternative + wedge]),
      p([*The buyer's default is “we already have Northstar” or a free GA property* plus a spreadsheet. _“We also do funnels”_ does not move them. The defensible wedge is the _combination_: *tag-free capture + replay + funnels with zero engineering setup* → _“analytics you can install yourself before lunch — no tracking plan, no engineers.”_]),
    ),

    section("04", [Positioning recommendation], kicker: "One sentence that does the work",
      quote-pull(
        [For product and growth teams who can't get engineering time for a tracking plan, Acme is analytics you install yourself in five minutes — it captures every interaction with no event tagging, so you get funnels and session replay without writing or maintaining instrumentation. Unlike Northstar or a hand-built GA setup, there is nothing to instrument and nothing to keep in sync. It also masks PII by default, so you can point it at production safely.],
        cite: "The pitch",
      ),
      p([Feature breadth moves from _the pitch_ to _a closing proof point_.]),
    ),

    section("05", [Homepage copy rewrite], kicker: "Reorder, mostly don't rewrite",
      h3([5.1 Hero — the wedge, proof-forward]),
      dl(
        ([H1], ["Product analytics you install yourself — no tracking plan, no engineers."]),
        ([Sub], ["Drop one snippet and Acme captures every click and funnel automatically. PII is masked by default. Funnels, retention, and session replay in one tool — live in about five minutes."]),
        ([Primary CTA], [#ic[Start free — no card, no sales call] (self-serve trial)]),
        ([Secondary CTA], [#ic[Watch a 90-second product tour]]),
      ),
      callout("Do NOT",
        [Make “Book a demo” the first and only thing a cold visitor can do. Keep the feature-led hero (“All your product analytics in one place”) as the A/B challenger, not the default.],
        warn: true),
      h3([5.2 Section order — the real fix]),
      ol(
        [*Hero* (above).],
        [*Live product moment* — an autoplaying 12-second capture-to-funnel clip, or an interactive sandbox. _Proof beats promise; this single thing kills the “unproven” read faster than any sentence on the page._],
        [*“Is it safe to point at production?”* — name the objection out loud, then answer it: default PII masking, DPA, data residency, what is and isn't stored.],
        [*Guarantee* — promoted from buried FAQ to a headline block: “Cancel in two clicks, prorated refund, export everything.”],
        [*How zero-instrumentation works* (one diagram).],
        [*Funnels / replay / retention* — the feature breadth, now as proof, not pitch.],
        [*Pricing* (transparent, one default plan; last, not first).],
        [*Who's behind this* (named team, changelog, status page).],
      ),
      p([*Never gate the only path behind a demo.* A demo CTA can coexist with self-serve — but “Start free” must be the primary action above the fold.]),
    ),

    section("06", [Pricing page — confusion ledger], kicker: "Four documents fighting on one page",
      p([The pricing page confuses readers because it is simultaneously four incompatible documents, each sabotaging the others:]),
      ol(
        [A SaaS price sheet (three tiers, per-seat-ish framing).],
        [A usage meter (per tracked user, overage per event, sampling caveats).],
        [An enterprise gate (“contact us” for the things buyers actually need).],
        [A capability flex (an unsourced “2× more accurate than the category leaders”).],
      ),
      p([Document 2 negates Document 1. Document 3 hides the answer to “what's my downside?” The page answers neither _what will I pay per month?_ nor _what happens when I exceed a limit?_]),
      h3([6.1 Confusion ledger — every contradiction, named]),
      etable(
        columns: (1fr, 1.25fr, 1.25fr),
        head: ([Confusion], [Exact conflicting copy], [Why it breaks the buyer]),
        rows: (
          ([Flat vs. usage], ["simple flat plans" + "billed per tracked user, \$0.002 / extra event"], [Opposite billing models in one phrase. Buyer can't predict spend.]),
          ([Cross-page price mismatch], [Home "from \$49/mo" vs pricing "Starter \$79/mo"], [Two headline prices contradict between pages seen in one session. Reads as bait.]),
          (["Unlimited" that isn't], ["unlimited sessions" + "fair-use sampling above 100k/mo"], [A carve-out on an “unlimited” claim. Under-disclosed; erodes trust on the page where trust matters most.]),
          ([Plan vs. add-on sprawl], [3 tiers + replay add-on + residency add-on + seats + events], [~5 orthogonal billing axes. Needs a spreadsheet. Conversion killer.]),
          ([Accuracy figure drifts], [hero "2× more accurate" / FAQ "up to 40% fewer blind spots"], [No single credible number; reads as marketing math.]),
          ([Unsourced benchmark], ["beats the category leaders" with no method, no source], [Strong claim, no evidence. On a trust-fragile page, unsourced flexes reduce credibility.]),
          ([Hidden enterprise wall], ["SSO, DPA, residency: contact sales"], [The things a serious buyer must have are exactly the things behind a gate. Stalls evaluation.]),
          ([Trial terms unclear], ["14-day trial" but card required and auto-converts], [A “free trial” that bills silently on day 15 is a refund and chargeback engine.]),
          ([Seat math undefined], ["per editor" but viewers/“contributors” undefined], [Buyer can't compute team cost. Procurement stalls.]),
          ([Annual lock framing], ["save 20% annual" shown as the only price], [Monthly price hidden makes the entry cost feel higher than it is.]),
        ),
      ),
      h3([6.2 What a fixed pricing page looks like — structure, not numbers]),
      p([No price numbers are prescribed here: a real engagement would set them from willingness-to-pay evidence; the correct output is a structure plus a price test, not a number.]),
      ol(
        [*One sentence at the top declaring the model:* _“You pay per tracked user. Here is the rule and a worked example.”_ Pick one model. Never show two.],
        [*One value metric, one default plan.* Lead with a single blended price stated as a ceiling (“you never pay more than \$X / 1k tracked users”). Push tiers behind a “Need volume or SSO? →” link. Max three plans visible.],
        [*A cost calculator, not a static tier table.* Input: monthly tracked users. Output: your bill here vs. the obvious alternative.],
        [*An honest downside box, stated by you before the buyer finds it.* “Over your plan? You're sampled, not surprise-billed — here's exactly when.”],
        [*Free trial with no card*, or say plainly “card required, cancel anytime, we email before we bill.” Owning this builds trust; hiding it destroys it.],
        [*Kill the accuracy claim or cite it* with a defined, reproducible benchmark.],
      ),
    ),

    section("07", [Trust-fix checklist], kicker: "Highest leverage, ranked",
      ol(
        [*Ship a no-card self-serve trial (or an interactive sandbox) before any demo ask.* Usable proof beats all copy.],
        [*Make the team legible.* Real names, faces, a public changelog and status page. “Unproven” dies when the page shows people and momentum.],
        [*Lead with the guarantee, not the feature list.*],
        [*Make the privacy claim true and default*, then say so on the homepage, not only in a buried FAQ.],
        [*Replace the three unknown logos* with one concrete, attributed result (“Team X cut analytics setup from 3 weeks to a day”).],
        [*Put a real product moment above the fold* — autoplaying capture-to-funnel clip or sandbox.],
        [*Commit to one ICP* (unknown \#4) and cut the other two heroes' worth of mixed signals.],
        [*Make the homepage and pricing page agree on every number* — single source of truth.],
      ),
    ),

    section("08", [Next actions], kicker: "Founder-executable, this week",
      ol(
        [Decide flat vs. usage billing; write the one-sentence rule + one worked invoice (unknown \#5).],
        [Install the snippet on three real sites yourself; document true time-to-value (unknown \#1).],
        [Make homepage and pricing agree on every number — single source of truth (cross-page mismatch).],
        [Stand up the no-card trial or an interactive sandbox (highest single ROI).],
        [Run the 8-PM / 5-unmoderated-test “would you start this trial, what stops you?” probe (unknown \#2).],
        [Read existing trial-signup free-text answers; classify the real ICP (unknown \#4).],
        [Reorder the homepage per §5.2; collapse pricing to ≤3 visible plans; add the cost calculator and the honest overage box.],
        [Run a Van Westendorp / Gabor-Granger WTP probe with target buyers *before* finalizing any price number.],
      ),
    ),

    section("09", [Kill / pivot / narrow rules], kicker: "When the diagnosis is wrong",
      rule-def([Belief model],
        [After shipping the no-card trial + legible team + guarantee-forward copy, if cold-traffic qualitative still fails — *\<3 of 8 target PMs say they'd start the trial*, with “don't trust capturing everything / don't believe the accuracy claim / can't tell what I'd pay” as the dominant objection — the blocker is the _offer and proof model itself_, not the copy. *Pivot:* lead with a free, capped, no-account sandbox tier, *or narrow hard* to the no-instrumentation segment and stop pitching general analytics buyers.]),
      rule-def([Offer architecture],
        [After de-confusing the pricing page, if ≥half of probe respondents still say _“I can't tell what I'd pay”_ or _“the overage thing makes it feel risky,”_ the per-tracked-user metered model is unsellable to cold buyers. *Pivot* to a flat, predictable plan with a generous cap, or narrow to the segment whose volume is stable enough to tolerate metering.]),
    ),
  ),

  appendices: (
    appendix("appendix-a", "Appendix A", [Sample extracted copy], meta: "fictional — illustrative only",
      h3([A.1 Homepage]),
      ul(
        [*Hero H1:* “All your product analytics in one place.”],
        [*Sub:* “Funnels, retention, dashboards, and session replay — without the spreadsheet.”],
        [*CTAs:* “Book a demo” (×3), “Talk to sales”, “See plans”.],
        [*Social proof:* three unfamiliar logos; one unattributed quote (“It changed how we work.”).],
        [*Benefits:* Auto-capture; Funnels; Retention; Heatmaps; Replay; “Privacy-first”.],
        [*Team:* one paragraph, no names; no changelog or status link.],
      ),
      h3([A.2 Pricing page (sample)]),
      ul(
        [*Tiers:* Starter “\$79/mo”; Growth “\$249/mo”; Scale “contact sales”.],
        [*Meter:* “billed per tracked user; \$0.002 per extra event; fair-use sampling above 100k sessions/mo”.],
        [*Trial:* “14-day free trial” (card required; auto-converts).],
        [*Add-ons:* session replay; EU data residency; SSO/DPA “contact sales”.],
        [*Flex:* “2× more accurate than the category leaders” (no method, no source).],
      ),
      h3([A.3 Competitor names used above]),
      ul(
        [“Northstar”, “Metricly”, “Funnelhouse”, “Replaylab” are *invented placeholders* for this sample and do not refer to real companies.],
      ),
    ),

    appendix("appendix-b", "Appendix B", [Notes on this sample],
      ul(
        [This is a *sample* report shipped with the template. The product, the copy, the findings, the numbers and the competitor names are all *fictional* and exist only to exercise every block type (key–value list, ordered/unordered lists, tables with tags, callouts, pull quotes, definition rules, appendices).],
        [The subject domain uses the reserved #ic[.example] TLD specifically so it cannot be mistaken for a real site.],
        [To use this as a real teardown, replace the data in #ic[report.typ] with real, sourced findings and keep an honest evidence/citation note here in its place.],
        [No real sources were consulted; nothing here should be cited or relied upon.],
      ),
    ),
  ),
)
